spaceship-labs/actual-front

app/views/checkout/order-policies.html
app/views/quotations/quotation-texts.html

Cambio en el porcentaje de garantía

texts changed to 36 percent

---

app/scripts/services/quotationservice.js

Edited traffic data on kids.
* `app/scripts/services/quotationservice.js`
None

Ticket-kids | Changed and Added values to traffic

---

app/scripts/services/quotationservice.js

Edited traffic data.
* `app/scripts/services/quotationservice.js`
None

Ticket | Edited and Added values to traffic

---

app/views/checkout/order-policies.html

Fix "docimicilio" word.
`app/views/checkout/order-policies.html`
None

fix "domicilio" spelling

---

app/views/checkout/order-policies.html

Fix "docimicilio" word.
`app/views/checkout/order-policies.html`
None

fix "domicilio" text spelling

---

app/views/checkout/order-policies.html

Always adds the authorized person to receive order in address
`app/views/checkout/order-policies.html`
None

Add authorized person in address to order policy.

---

app/scripts/controllers/product.js

Hides the immediate delivery on store option from quotation.
* ` app/scripts/controllers/product.js `

Added filter to remove immediate deliveries

---

app/scripts/controllers/product.js

Hides the immediate delivery on store option from quotation.
* ` app/scripts/controllers/product.js `

Added filter to deliveries groups by pandemy

---

app/scripts/controllers/reports/quotations.js
app/scripts/services/formatservice.js

Fix field `Cierre` showed on table and Excel report; previously showed tracing date.
* `controllers/reports/quotations.js`
* `services/formatservice.js `

Fix quotation estimated close date

---

app/scripts/controllers/reports/quotations.js
app/scripts/directives/table-list.js
app/views/reports/quotation-report-filters.html
app/views/reports/quotations.html

* Add the close date filter to view
* Add the `closeDate` field to directive `table-list` 
* Add pickaday handler for `closeDateRange`
* `controllers/reports/quotation.js`
* `directives/table-list.js`
* `views/reports/quotation-report`

Add close date to filters

---

app/scripts/controllers/quotations/edit.js

Throw error when delivery date is before today; this error makes the user no longer have option to continue until delivery date got fixed

Throw error when day has passed

---

app/scripts/services/paymentOptionsConfig.js

enable 18 msi AH

---

app/scripts/services/paymentOptionsConfig.js

enable 18-msi kids

---

app/views/checkout/order.html

Se tag  para párrafo de téxto que imprima mensaje en el recibo de cliente desde order.html
Se genera vista en la impresión de recibo para el cliente 
Al realizar click en botón "Imprimir recibo" para generar pdf de la información
Revisar test de vista en rama production
None
None

Adición de mensaje en order.html

---

app/styles/main.css
app/views/checkout/order.html

Se agregan estilos para resaltar  párrafo de téxto que imprima mensaje en el recibo de cliente desde order.html
Se genera vista en la impresión de recibo para el cliente 
Al realizar click en botón "Imprimir recibo" para generar pdf de la información
Revisar test de vista en rama production
None
None

Resaltar mensaje de texto en order.html

---

app/styles/main.css
app/views/checkout/order.html

Se agregan estilos para resaltar  párrafo de téxto que imprima mensaje en el recibo de cliente desde order.html
Se genera vista en la impresión de recibo para el cliente 
Al realizar click en botón "Imprimir recibo" para generar pdf de la información
Revisar test de vista en rama production-kids
None
None

Resaltar mensaje de texto en order.html en rama prodution-kids

---

app/views/checkout/order.html
app/views/quotations/edit.html
app/views/quotations/quotation-seller-info.html
package.json

…on-seller-info.html de la rama prod## Feat: Modificación de datos vendedor -> Interiorista
Visualización del vendedor como interiorista en sitio web y en la impresión de las cotizaciones y pedidos
Seleccionar en menú las opciones de Pedidos, Cotización y Oportunidades en sitio web, y en el despligue, ir a la sección de la información para ubicar los datos del "Vendedor o Asesor de Interiores" como "Interiorista".
Revisón en documentos order.html, edit.html y quotation-seller-info.html + adición del dato @1.4.1 en poininstall del package.json  
Test de pruebas en rama feat/name-interior-production-kids
None
None

Modificación de subtitulo vendedor en cotizaciones y pedidos 

---

app/views/checkout/order.html

Visualizar leyenda: "Si el pedido contiene varios productos y diferentes fechas. Se realizará una sola entrega consolidando sus
productos en la ultima fecha que aparezca en su pedido. Si desea entregas parciales podrá solicitarlo sin cargo
extra en el teléfono: 998 246 0845" en order.html
Visualización en inforación de la número de orden en actual-front home
http://localhost:9000/checkout/order/(seleccionando una orden)
Revisar principalmente en oursales.html de la rama feat/new-legend-production
None
None

Adición de leyenda en documento orden.html de production

---

app/views/checkout/order.html

Visualizar leyenda: "Si el pedido contiene varios productos y diferentes fechas. Se realizará una sola entrega consolidando sus
productos en la ultima fecha que aparezca en su pedido. Si desea entregas parciales podrá solicitarlo sin cargo
extra en el teléfono: 998 246 0845" en order.html
Visualización en inforación de la número de orden en actual-front kids
http://localhost:9000/checkout/order/(seleccionando una orden)
Revisar principalmente en oursales.html de la rama feat/new-legend-kids
None
None

Adición de leyenda en documento orden.html de production_kids

---

app/scripts/services/quotationservice.js
app/views/quotations/transfers-table.html

Visualizar los recomendando en tráfico para internet y mérida en web
Visualización en pointer de web
Documento quotationservice.js en rama feat/new-recomendation-production-kids
Revisar en rama: production-kids
None
None

Adición de datos recomendando en production-kids

---

app/scripts/services/quotationservice.js
app/views/quotations/transfers-table.html

Visualizar los recomendando en tráfico para internet y mérida en web
Visualización en pointer de web
Documento quotationservice.js en rama feat/new-recomendation-production
Revisar en rama: production
None
None

Adición de datos recomendando

---

app/scripts/services/quotationservice.js
app/views/quotations/edit.html

Visualizar datos de tráfico específicos y modificación de datos de vigencia
Implementaciones en producction  para front
Manipulación de datos en quotationservice.js para el tráfico y edit.html para frase de vigencia
Revisar test en rama Feat/traffic-features
None
None

Modificación de datos de tráfico y modificación de vigencia
